#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.secrets.username %>
  password: <%= Rails.application.secrets.password %>
  host: <%= Rails.application.secrets.host %>

development:
  <<: *default
  database: <%= Rails.application.secrets.app_name %>_development

test:
  <<: *default
  database: <%= Rails.application.secrets.app_name %>_test

production:
  <<: *default
  database: <%= Rails.application.secrets.app_name %>_production
