# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a75f7f7ea9eb52d43d6c10564d3163170b3687f7213eef1f480c07fa235624a404cdcbec670a130f669ef054b5b97a3eb8186457749bbc80c48329ec1297cd99

test:
  secret_key_base: be138c88804cacb2074f27c7fb93c2854f4c808c560af0bd1ac0b176d4b1c4b7f8f64b01cbbe66135b07726e628b56a38d22b93cb695ce29d1b92628f03d6e2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
